# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jarvis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jarvis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cjarvis.proto\x12\x06jarvis\"Q\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0b\n\x03llm\x18\x03 \x01(\t\x12\x13\n\x0breflect_llm\x18\x04 \x01(\t\"6\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x16\n\x0elow_confidence\x18\x02 \x01(\x08\"E\n\rIngestRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nsource_url\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"!\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rMemoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"<\n\x0eMemoryResponse\x12*\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x19.jarvis.ConversationEntry\"F\n\x11\x43onversationEntry\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf6\x01\n\rJarvisService\x12\x31\n\x04\x43hat\x12\x13.jarvis.ChatRequest\x1a\x14.jarvis.ChatResponse\x12\x37\n\x06Ingest\x12\x15.jarvis.IngestRequest\x1a\x16.jarvis.IngestResponse\x12:\n\tGetMemory\x12\x15.jarvis.MemoryRequest\x1a\x16.jarvis.MemoryResponse\x12=\n\x0c\x44\x65leteMemory\x12\x15.jarvis.MemoryRequest\x1a\x16.jarvis.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jarvis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=24
  _globals['_CHATREQUEST']._serialized_end=105
  _globals['_CHATRESPONSE']._serialized_start=107
  _globals['_CHATRESPONSE']._serialized_end=161
  _globals['_INGESTREQUEST']._serialized_start=163
  _globals['_INGESTREQUEST']._serialized_end=232
  _globals['_INGESTRESPONSE']._serialized_start=234
  _globals['_INGESTRESPONSE']._serialized_end=267
  _globals['_MEMORYREQUEST']._serialized_start=269
  _globals['_MEMORYREQUEST']._serialized_end=301
  _globals['_MEMORYRESPONSE']._serialized_start=303
  _globals['_MEMORYRESPONSE']._serialized_end=363
  _globals['_CONVERSATIONENTRY']._serialized_start=365
  _globals['_CONVERSATIONENTRY']._serialized_end=435
  _globals['_DELETERESPONSE']._serialized_start=437
  _globals['_DELETERESPONSE']._serialized_end=470
  _globals['_JARVISSERVICE']._serialized_start=473
  _globals['_JARVISSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
